### ISSUE TITLE
Issue while iterting xml file

### ISSUE THREAD

**Issue by desh130** [moshekaplan/palo_alto_firewall_analyzer#60]
alo_alto_firewall_analyzer.validators.misleading_objects - INFO - (9/13) Checking PDX Office's Address objects
palo_alto_firewall_analyzer.validators.misleading_objects - INFO - (10/13) Checking HVW DC's Address objects
palo_alto_firewall_analyzer.validators.misleading_objects - INFO - (11/13) Checking PDX's Address objects
palo_alto_firewall_analyzer.validators.misleading_objects - INFO - (12/13) Checking vor0506df01's Address objects
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Pan_Cleaner\pan_analyzer.exe\__main__.py", line 7, in <module>
  File "C:\Users\desh1\AppData\Roaming\Python\Python311\site-packages\palo_alto_firewall_analyzer\scripts\pan_analyzer.py", line 193, in main
    problems, total_problems = run_policy_validators(validators, profilepackage, output_fname)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desh1\AppData\Roaming\Python\Python311\site-packages\palo_alto_firewall_analyzer\scripts\pan_analyzer.py", line 66, in run_policy_validators
    validator_problems = validator_function(profilepackage)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desh1\AppData\Roaming\Python\Python311\site-packages\palo_alto_firewall_analyzer\validators\misleading_objects.py", line 49, in find_misleading_addresses
    ip_address = entry_value.split('/', 1)[0]
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'split'

**Comment by moshekaplan** [comment]
This appears to have the exact same error as #59, so I am going to close it out as a duplicate.
